image: "docker.elastic.co/kibana/kibana"
imageTag: "7.10.2"
imagePullPolicy: "IfNotPresent"

service:
  type: NodePort
  loadBalancerIP: ""
  port: 5601
  nodePort: "30037"
  labels: {}
  annotations: {}
  # cloud.google.com/load-balancer-type: "Internal"
  # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  # service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  # service.beta.kubernetes.io/cce-load-balancer-internal-vpc: "true"
  loadBalancerSourceRanges: []
  # 0.0.0.0/0
  httpPortName: http